' ******************************************************************************
' swxJRNL.swj - journal recorded on 05/15/20 by ¹ùÃÞÈñ
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = _
Application.SldWorks

swApp.ActivateDoc2 "×°ÅäÌå1.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.010669559955588001, 0.81151846678151107
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.010669559955588001, 0.12022495804170534
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02254217963281975
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0071130399703920009, 0.030056239510426335
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.015028119755213168
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.010669559955588001, 0.052598419143246089
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.010669559955588001, 0.052598419143246089
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.017782599925980004, 0.090168718531279002
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0071130399703920009, 0.052598419143246089
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0071130399703920009, 0.030056239510426335
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02254217963281975
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0035565199851960005, 0.0075140598776065838
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0035565199851960005, 0.02254217963281975
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0035565199851960005, 0.030056239510426335
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.03757029938803292
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0075140598776065838
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0035565199851960005, 0.090168718531279002
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.052598419143246089
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.010669559955588001, 0.067626538898459251
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0071130399703920009, 0.06011247902085267
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.010669559955588001, 0.10519683828649218
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.067626538898459251
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0071130399703920009, 0.06011247902085267
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.052598419143246089
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.067626538898459251
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02254217963281975
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.015028119755213168
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0075140598776065838
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.015028119755213168
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010669559955588001, 0.015028119755213168
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035565199851960005, 0.0075140598776065838
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.014226079940784002, 0.03757029938803292
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.039121719837156003, 0.030056239510426335
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010669559955588001, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.042678239822352006, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010669559955588001, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.035565199851960008, 0.0075140598776065838
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.014226079940784002, 0.015028119755213168
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010669559955588001, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.021339119911176003, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035565199851960005, -0.0075140598776065838
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010669559955588001, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010669559955588001, -0.030056239510426335
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035565199851960005, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0071130399703920009, -0.045084359265639501
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0071130399703920009, -0.045084359265639501
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0071130399703920009, -0.03757029938803292
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035565199851960005, -0.015028119755213168
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.014226079940784002, -0.11271089816409877
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035565199851960005, -0.015028119755213168
boolstatus = Part.Extension.SelectByID2("", "EDGE", 0.11234937636511688, -0.021211781438168487, -0.14348499010395699, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("", "EDGE", -0.11080623964278402, -0.012157075085525548, -0.14222560842108578, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SketchBoxSelect("0.000000", "0.000000", "0.000000", "0.000000", "0.000000", "0.000000")
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.11175306084925296, -0.017521909588381845, -0.14248906519202365, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("", "FACE", -0.11087832835180222, -0.021906666633029204, -0.14269627523674444, True, 0, Nothing, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.015324842212633171, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.035565199851960008, 0.05363694774421611, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.021339119911176003, 0.061299368850532686, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.021339119911176003, 0.04597452663789952, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.014226079940784002, 0.030649684425266343, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.014226079940784002, 0.02298726331894976, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0.030649684425266343, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.021339119911176003, 0.05363694774421611, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0.030649684425266343, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0.030649684425266343, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010669559955588001, 0.03831210553158293, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0.03831210553158293, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02298726331894976, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0.015324842212633171, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.068961789956849276, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0.076624211063165859, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03831210553158293, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.015324842212633171, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.017782599925980004, 0, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.024895639896372002, 0, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.021339119911176003, -0.0076624211063165857, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.035565199851960008, -0.05363694774421611, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.032008679866764006, -0.061299368850532686, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.028452159881568004, -0.061299368850532686, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.014226079940784002, -0.02298726331894976, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.021339119911176003, -0.030649684425266343, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010669559955588001, -0.015324842212633171, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, -0.0076624211063165857, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, -0.0076624211063165857, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010669559955588001, -0.0076624211063165857, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010669559955588001, -0.0076624211063165857, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.014226079940784002, 0, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.028452159881568004, -0.02298726331894976, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.046234759807548001, -0.015324842212633171, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.060460839748332003, -0.03831210553158293, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.096026039600292004, -0.030649684425266343, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.049791279792744003, -0.015324842212633171, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.046234759807548001, 0, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.024895639896372002, 0, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.014226079940784002, 0, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.028452159881568004, 0, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.032008679866764006, 0, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.035565199851960008, 0, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.039121719837156003, -0.0076624211063165857, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.021339119911176003, 0, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010669559955588001, -0.015324842212633171, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.017782599925980004, 0, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010669559955588001, 0, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.014226079940784002, 0, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.014226079940784002, 0, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.021339119911176003, 0, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010669559955588001, 0.02298726331894976, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010669559955588001, 0.0076624211063165857, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0.015324842212633171, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.024895639896372002, 0.015324842212633171, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.028452159881568004, 0.02298726331894976, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.039121719837156003, 0.030649684425266343, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.017782599925980004, 0.015324842212633171, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0.0076624211063165857, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0, -0.028147646083368727, 0.00061430972168352582, -0.15459399216655356
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.056904319763136008, -0.091949053275799039, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.021339119911176003, -0.02298726331894976, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010669559955588001, -0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010669559955588001, -0.02298726331894976, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010669559955588001, 0, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.024895639896372002, -0.02298726331894976, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.024895639896372002, -0.02298726331894976, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.035565199851960008, -0.03831210553158293, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.021339119911176003, -0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.049791279792744003, -0.05363694774421611, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.053347799777940005, -0.04597452663789952, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.035565199851960008, -0.030649684425266343, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010669559955588001, 0, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, 0, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010669559955588001, -0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.014226079940784002, -0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.021339119911176003, 0, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.021339119911176003, -0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.028452159881568004, -0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.028452159881568004, 0, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.046234759807548001, -0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.028452159881568004, -0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.096026039600292004, -0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.053347799777940005, -0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.074686919689116005, -0.030649684425266343, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.056904319763136008, -0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.053347799777940005, -0.02298726331894976, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.056904319763136008, -0.02298726331894976, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.056904319763136008, -0.030649684425266343, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.053347799777940005, -0.02298726331894976, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.046234759807548001, -0.02298726331894976, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.049791279792744003, -0.03831210553158293, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.039121719837156003, -0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010669559955588001, -0.05363694774421611, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.014226079940784002, -0.03831210553158293, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.032008679866764006, -0.05363694774421611, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.028452159881568004, -0.061299368850532686, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.024895639896372002, -0.03831210553158293, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010669559955588001, -0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, -0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.05363694774421611, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.091949053275799039, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.091949053275799039, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.05363694774421611, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.030649684425266343, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02298726331894976, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.061299368850532686, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.11493631659474879, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, -0.03831210553158293, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02298726331894976, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, -0.03831210553158293, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02298726331894976, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, -0.03831210553158293, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, -0.030649684425266343, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, -0.03831210553158293, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010669559955588001, -0.02298726331894976, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, -0.030649684425266343, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, -0.02298726331894976, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, -0.02298726331894976, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, -0.02298726331894976, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, -0.03831210553158293, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, -0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.030649684425266343, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, -0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03831210553158293, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02298726331894976, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.030649684425266343, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.068961789956849276, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.084286632169482456, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, -0.04597452663789952, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.061299368850532686, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, -0.030649684425266343, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.030649684425266343, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, -0.02298726331894976, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, -0.04597452663789952, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, -0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, -0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, -0.02298726331894976, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, -0.030649684425266343, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, -0.02298726331894976, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.017782599925980004, -0.030649684425266343, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, -0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010669559955588001, 0, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010669559955588001, 0, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, -0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, -0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.014226079940784002, -0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010669559955588001, -0.02298726331894976, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, -0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, -0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.021339119911176003, -0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.014226079940784002, 0.030649684425266343, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02298726331894976, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0.03831210553158293, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.04597452663789952, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0.030649684425266343, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.030649684425266343, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, 0.061299368850532686, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03831210553158293, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0.03831210553158293, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02298726331894976, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.05363694774421611, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0.03831210553158293, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0.084286632169482456, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010669559955588001, 0.14558600102001512, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0.091949053275799039, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.16091084323264832, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.15324842212633172, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.19156052765791465, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.16091084323264832, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.12259873770106537, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.05363694774421611, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.076624211063165859, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02298726331894976, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0.015324842212633171, -0.0042803528566395244, 0, -0.073746086167091107
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.021339119911176003, 0.16857326433896491, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.014226079940784002, 0.04597452663789952, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.014226079940784002, 0.05363694774421611, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.014226079940784002, 0.03831210553158293, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010669559955588001, 0.015324842212633171, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0.0076624211063165857, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0.015324842212633171, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010669559955588001, 0, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010669559955588001, 0, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.021339119911176003, 0, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.032008679866764006, -0.04597452663789952, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.021339119911176003, -0.030649684425266343, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.014226079940784002, -0.02298726331894976, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.014226079940784002, -0.02298726331894976, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.014226079940784002, -0.015324842212633171, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010669559955588001, 0, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, -0.015324842212633171, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, -0.0076624211063165857, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.014226079940784002, 0, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0.0076624211063165857, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0.0076624211063165857, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010669559955588001, 0.015324842212633171, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0.015324842212633171, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0.0076624211063165857, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0.015324842212633171, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0.0076624211063165857, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0.015324842212633171, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0.0076624211063165857, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0.0076624211063165857, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0.0076624211063165857, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0.0076624211063165857, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0.0076624211063165857, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0.0076624211063165857, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0.0076624211063165857, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0.015324842212633171, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0.015324842212633171, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0.0076624211063165857, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0.015324842212633171, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0.0076624211063165857, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02298726331894976, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, -0.10727389548843222, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, -0.11493631659474879, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, -0.05363694774421611, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.015324842212633171, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, -0.0076624211063165857, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0076624211063165857, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03831210553158293, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0076624211063165857, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.015324842212633171, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0076624211063165857, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02298726331894976, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02298726331894976, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, -0.03831210553158293, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02298726331894976, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0076624211063165857, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, -0.02298726331894976, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.017782599925980004, -0.076624211063165859, 0.082852630991055776, 0.002999999999872216, -0.1450639756293981
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.09625000000005457, 0.00098919088745219597, -0.12956661435896422, True, 0, Nothing, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0.015324842212633171, 0.09625000000005457, 0.00091163032666941035, -0.12951220082709369
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03831210553158293, 0.09625000000005457, 0.00091163032666941035, -0.12951220082709369
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.18389810655159808, 0.09625000000005457, 0.00091163032666941035, -0.12951220082709369
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.05363694774421611, 0.09625000000005457, 0.00091163032666941035, -0.12951220082709369
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, 0.09625000000005457, 0.00091163032666941035, -0.12951220082709369
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, 0.09625000000005457, 0.00091163032666941035, -0.12951220082709369
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, 0.09625000000005457, 0.00091163032666941035, -0.12951220082709369
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.015324842212633171, 0.09625000000005457, 0.00091163032666941035, -0.12951220082709369
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, 0.068961789956849276, 0.09625000000005457, 0.00091163032666941035, -0.12951220082709369
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.030649684425266343, 0.09625000000005457, 0.00091163032666941035, -0.12951220082709369
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.030649684425266343, 0.09625000000005457, 0.00091163032666941035, -0.12951220082709369
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03831210553158293, 0.09625000000005457, 0.00091163032666941035, -0.12951220082709369
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0.03831210553158293, 0.09625000000005457, 0.00091163032666941035, -0.12951220082709369
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0.02298726331894976, 0.09625000000005457, 0.00091163032666941035, -0.12951220082709369
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, 0.05363694774421611, 0.09625000000005457, 0.00091163032666941035, -0.12951220082709369
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0.068961789956849276, 0.09625000000005457, 0.00091163032666941035, -0.12951220082709369
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010669559955588001, 0.068961789956849276, 0.09625000000005457, 0.00091163032666941035, -0.12951220082709369
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.05363694774421611, 0.09625000000005457, 0.00091163032666941035, -0.12951220082709369
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.04597452663789952, 0.09625000000005457, 0.00091163032666941035, -0.12951220082709369
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0.0076624211063165857, 0.09625000000005457, 0.00091163032666941035, -0.12951220082709369
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0.02298726331894976, 0.09625000000005457, 0.00091163032666941035, -0.12951220082709369
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, 0.068961789956849276, 0.09625000000005457, 0.00091163032666941035, -0.12951220082709369
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.04597452663789952, 0.09625000000005457, 0.00091163032666941035, -0.12951220082709369
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0.0076624211063165857, 0.09625000000005457, 0.00091163032666941035, -0.12951220082709369
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123, True, 0, Nothing, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0076624211063165857, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0076624211063165857, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.030649684425266343, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02298726331894976, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.015324842212633171, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, -0.015324842212633171, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03831210553158293, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03831210553158293, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.015324842212633171, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.030649684425266343, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0076624211063165857, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.015324842212633171, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0076624211063165857, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.015324842212633171, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02298726331894976, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0076624211063165857, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.015324842212633171, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0076624211063165857, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02298726331894976, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.04597452663789952, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.030649684425266343, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, -0.02298726331894976, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, -0.015324842212633171, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, -0.0076624211063165857, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, -0.015324842212633171, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.014226079940784002, -0.02298726331894976, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, -0.015324842212633171, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, -0.0076624211063165857, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010669559955588001, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0.015324842212633171, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.015324842212633171, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.024895639896372002, 0.0076624211063165857, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010669559955588001, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.017782599925980004, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.014226079940784002, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010669559955588001, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010669559955588001, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.014226079940784002, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, -0.0076624211063165857, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.014226079940784002, -0.015324842212633171, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.014226079940784002, -0.015324842212633171, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, -0.0076624211063165857, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010669559955588001, -0.0076624211063165857, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010669559955588001, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, -0.0076624211063165857, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.024895639896372002, -0.02298726331894976, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.017782599925980004, -0.015324842212633171, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.017782599925980004, -0.02298726331894976, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.017782599925980004, -0.0076624211063165857, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.035565199851960008, -0.0076624211063165857, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.021339119911176003, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.028452159881568004, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010669559955588001, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.039121719837156003, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.021339119911176003, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.014226079940784002, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010669559955588001, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010669559955588001, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.017782599925980004, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, -0.0076624211063165857, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.014226079940784002, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010669559955588001, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.014226079940784002, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.017782599925980004, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010669559955588001, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010669559955588001, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, 0.0076624211063165857, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, 0.0076624211063165857, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, 0.015324842212633171, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, 0.0076624211063165857, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.014226079940784002, 0.05363694774421611, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, 0, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0.0076624211063165857, 0.090249999999912234, 0.00082964885574199343, -0.12686973759662123
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.14581731939303602, 0, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.046234759807548001, 0, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010669559955588001, -0.0076624211063165857, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, -0.015324842212633171, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035565199851960005, 0, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.021339119911176003, -0.03831210553158293, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.021339119911176003, -0.02298726331894976, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.014226079940784002, -0.0076624211063165857, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.017782599925980004, 0, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.021339119911176003, -0.0076624211063165857, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, 0, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.014226079940784002, -0.0076624211063165857, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.014226079940784002, 0, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010669559955588001, 0, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.017782599925980004, 0.02298726331894976, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010669559955588001, 0.015324842212633171, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, 0.0076624211063165857, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010669559955588001, 0.0076624211063165857, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, 0.0076624211063165857, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.017782599925980004, 0.015324842212633171, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.024895639896372002, 0.015324842212633171, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.028452159881568004, 0, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.028452159881568004, 0, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.046234759807548001, 0, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.049791279792744003, -0.015324842212633171, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.039121719837156003, 0, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.035565199851960008, 0.02298726331894976, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.024895639896372002, -0.0076624211063165857, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.064017359733528012, -0.04597452663789952, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.064017359733528012, -0.02298726331894976, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.024895639896372002, -0.0076624211063165857, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071130399703920009, -0.0076624211063165857, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, -0.0076624211063165857, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.014226079940784002, -0.02298726331894976, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035565199851960005, 0, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03831210553158293, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0076624211063165857, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071130399703920009, 0.0076624211063165857, 0.090655440557263489, -3.2614537815334188e-005, -0.10979705826559893
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Part.ClearSelection2 True
swApp.ExitApp
End Sub
